server:
  port: 0

spring:
  application:
    name: media-upload
  kafka:
    producer:
      bootstrap-servers: localhost:29092
    consumer:
      bootstrap-servers: localhost:29092

  datasource:
    url: jdbc:h2:mem:dev
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      path: /h2

queue:
  aws: topic-aws
  azure: topic-azure


aws:
  accessKeyId: {ACCESS_KEY_AWS}
  secretKey: {SECRET_KEY_AWS}
  region: us-east-2

s3:
  bucketName: media-uploader-app

azure:
  connectionString: conn
  accountName: lipetest



