server:
  port: 0

spring:
  application:
    name: media-upload
  kafka:
    producer:
      bootstrap-servers: localhost:29092
    consumer:
      bootstrap-servers: localhost:29092

queue:
  aws: topic-aws
  azure: topic-azure